// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanCodeGenerator
{
    using System;
    
    internal sealed partial class PackageGuids
    {
        public const string guidCleanCodeGeneratorPackageString = "5958e231-12e3-454c-9bed-7b1caf69c5ac";
        public static Guid guidCleanCodeGeneratorPackage = new Guid(guidCleanCodeGeneratorPackageString);

        public const string guidCleanCodeGeneratorPackageCmdSetString = "1be5d7ed-3261-4fdf-be1b-8986b14f5a84";
        public static Guid guidCleanCodeGeneratorPackageCmdSet = new Guid(guidCleanCodeGeneratorPackageCmdSetString);
    }

    internal sealed partial class PackageIds
    {
        public const int ItemsSelectorWindowCommandId = 0x0100;
    }
}