// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanCodeGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CleanCodeGenerator.70d2ba1a-fac2-44c8-9d3d-bbaf49147e72";
        public const string Name = "CleanCodeGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alan Macgowan";
        public const string Tags = "";
    }
}
