// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeGenerator.b1442333-074c-4f9d-800c-77d5f4a664d9";
        public const string Name = "CodeGenerator";
        public const string Description = @"CodeGenerator for Clean Architecture solutions.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alan Macgowan";
        public const string Tags = "";
    }
}
